var spawn = require("child_process").spawn

var ret;
const proc = spawn("detectKeys.exe");
const propogate = false;

//Keycodes taken from here:
//https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
var lookupVkeys = {
    0x30: {name:"VK_0", common: "0"},
    0x31: {name:"VK_1", common: "1"},
    0x32: {name:"VK_2", common: "2"},
    0x33: {name:"VK_3", common: "3"},
    0x34: {name:"VK_4", common: "4"},
    0x35: {name:"VK_5", common: "5"},
    0x36: {name:"VK_6", common: "6"},
    0x37: {name:"VK_7", common: "7"},
    0x38: {name:"VK_8", common: "8"},
    0x39: {name:"VK_9", common: "9"},
    0x41: {name:"VK_A", common: "A"},
    0x42: {name:"VK_B", common: "B"},
    0x43: {name:"VK_C", common: "C"},
    0x44: {name:"VK_D", common: "D"},
    0x45: {name:"VK_E", common: "E"},
    0x46: {name:"VK_F", common: "F"},
    0x47: {name:"VK_G", common: "G"},
    0x48: {name:"VK_H", common: "H"},
    0x49: {name:"VK_I", common: "I"},
    0x4A: {name:"VK_J", common: "J"},
    0x4B: {name:"VK_K", common: "K"},
    0x4C: {name:"VK_L", common: "L"},
    0x4D: {name:"VK_M", common: "M"},
    0x4E: {name:"VK_N", common: "N"},
    0x4F: {name:"VK_O", common: "O"},
    0x50: {name:"VK_P", common: "P"},
    0x51: {name:"VK_Q", common: "Q"},
    0x52: {name:"VK_R", common: "R"},
    0x53: {name:"VK_S", common: "S"},
    0x54: {name:"VK_T", common: "T"},
    0x55: {name:"VK_U", common: "U"},
    0x56: {name:"VK_V", common: "V"},
    0x57: {name:"VK_W", common: "W"},
    0x58: {name:"VK_X", common: "X"},
    0x59: {name:"VK_Y", common: "Y"},
    0x5A: {name:"VK_Z", common: "Z"},
    0x01: {name:"VK_LBUTTON", common: "LBUTTON"},
    0x02: {name:"VK_RBUTTON", common: "RBUTTON"},
    0x03: {name:"VK_CANCEL", common: "CANCEL"},
    0x04: {name:"VK_MBUTTON", common: "MBUTTON"},
    0x05: {name:"VK_XBUTTON1", common: "XBUTTON1"},
    0x06: {name:"VK_XBUTTON2", common: "XBUTTON2"},
    0x08: {name:"VK_BACK", common: "BACK"},
    0x09: {name:"VK_TAB", common: "TAB"},
    0x0C: {name:"VK_CLEAR", common: "CLEAR"},
    0x0D: {name:"VK_RETURN", common: "RETURN"},
    0x10: {name:"VK_SHIFT", common: "SHIFT"},
    0x11: {name:"VK_CONTROL", common: "CONTROL"},
    0x12: {name:"VK_MENU", common: "MENU"},
    0x13: {name:"VK_PAUSE", common: "PAUSE"},
    0x14: {name:"VK_CAPITAL", common: "CAPSLOCK"},
    0x15: {name:"VK_KANA", common: "KANA"},
    0x15: {name:"VK_HANGUEL", common: "HANGUEL"},
    0x15: {name:"VK_HANGUL", common: "HANGUL"},
    0x16: {name:"VK_IME_ON", common: "IME_ON"},
    0x17: {name:"VK_JUNJA", common: "JUNJA"},
    0x18: {name:"VK_FINAL", common: "FINAL"},
    0x19: {name:"VK_HANJA", common: "HANJA"},
    0x19: {name:"VK_KANJI", common: "KANJI"},
    0x1A: {name:"VK_IME_OFF", common: "IME_OFF"},
    0x1B: {name:"VK_ESCAPE", common: "ESCAPE"},
    0x1C: {name:"VK_CONVERT", common: "CONVERT"},
    0x1D: {name:"VK_NONCONVERT", common: "NONCONVERT"},
    0x1E: {name:"VK_ACCEPT", common: "ACCEPT"},
    0x1F: {name:"VK_MODECHANGE", common: "MODECHANGE"},
    0x20: {name:"VK_SPACE", common: "SPACE"},
    0x21: {name:"VK_PRIOR", common: "PRIOR"},
    0x22: {name:"VK_NEXT", common: "NEXT"},
    0x23: {name:"VK_END", common: "END"},
    0x24: {name:"VK_HOME", common: "HOME"},
    0x25: {name:"VK_LEFT", common: "LEFT"},
    0x26: {name:"VK_UP", common: "UP"},
    0x27: {name:"VK_RIGHT", common: "RIGHT"},
    0x28: {name:"VK_DOWN", common: "DOWN"},
    0x29: {name:"VK_SELECT", common: "SELECT"},
    0x2A: {name:"VK_PRINT", common: "PRINT"},
    0x2B: {name:"VK_EXECUTE", common: "EXECUTE"},
    0x2C: {name:"VK_SNAPSHOT", common: "SNAPSHOT"},
    0x2D: {name:"VK_INSERT", common: "INSERT"},
    0x2E: {name:"VK_DELETE", common: "DELETE"},
    0x2F: {name:"VK_HELP", common: "HELP"},
    0x5B: {name:"VK_LWIN", common: "LWIN"},
    0x5C: {name:"VK_RWIN", common: "RWIN"},
    0x5D: {name:"VK_APPS", common: "APPS"},
    0x5F: {name:"VK_SLEEP", common: "SLEEP"},
    0x60: {name:"VK_NUMPAD0", common: "NUMPAD0"},
    0x61: {name:"VK_NUMPAD1", common: "NUMPAD1"},
    0x62: {name:"VK_NUMPAD2", common: "NUMPAD2"},
    0x63: {name:"VK_NUMPAD3", common: "NUMPAD3"},
    0x64: {name:"VK_NUMPAD4", common: "NUMPAD4"},
    0x65: {name:"VK_NUMPAD5", common: "NUMPAD5"},
    0x66: {name:"VK_NUMPAD6", common: "NUMPAD6"},
    0x67: {name:"VK_NUMPAD7", common: "NUMPAD7"},
    0x68: {name:"VK_NUMPAD8", common: "NUMPAD8"},
    0x69: {name:"VK_NUMPAD9", common: "NUMPAD9"},
    0x6A: {name:"VK_MULTIPLY", common: "MULTIPLY"},
    0x6B: {name:"VK_ADD", common: "ADD"},
    0x6C: {name:"VK_SEPARATOR", common: "SEPARATOR"},
    0x6D: {name:"VK_SUBTRACT", common: "SUBTRACT"},
    0x6E: {name:"VK_DECIMAL", common: "DECIMAL"},
    0x6F: {name:"VK_DIVIDE", common: "DIVIDE"},
    0x70: {name:"VK_F1", common: "F1"},
    0x71: {name:"VK_F2", common: "F2"},
    0x72: {name:"VK_F3", common: "F3"},
    0x73: {name:"VK_F4", common: "F4"},
    0x74: {name:"VK_F5", common: "F5"},
    0x75: {name:"VK_F6", common: "F6"},
    0x76: {name:"VK_F7", common: "F7"},
    0x77: {name:"VK_F8", common: "F8"},
    0x78: {name:"VK_F9", common: "F9"},
    0x79: {name:"VK_F10", common: "F10"},
    0x7A: {name:"VK_F11", common: "F11"},
    0x7B: {name:"VK_F12", common: "F12"},
    0x7C: {name:"VK_F13", common: "F13"},
    0x7D: {name:"VK_F14", common: "F14"},
    0x7E: {name:"VK_F15", common: "F15"},
    0x7F: {name:"VK_F16", common: "F16"},
    0x80: {name:"VK_F17", common: "F17"},
    0x81: {name:"VK_F18", common: "F18"},
    0x82: {name:"VK_F19", common: "F19"},
    0x83: {name:"VK_F20", common: "F20"},
    0x84: {name:"VK_F21", common: "F21"},
    0x85: {name:"VK_F22", common: "F22"},
    0x86: {name:"VK_F23", common: "F23"},
    0x87: {name:"VK_F24", common: "F24"},
    0x90: {name:"VK_NUMLOCK", common: "NUMLOCK"},
    0x91: {name:"VK_SCROLL", common: "SCROLL"},
    0xA0: {name:"VK_LSHIFT", common: "LSHIFT"},
    0xA1: {name:"VK_RSHIFT", common: "RSHIFT"},
    0xA2: {name:"VK_LCONTROL", common: "LCONTROL"},
    0xA3: {name:"VK_RCONTROL", common: "RCONTROL"},
    0xA4: {name:"VK_LMENU", common: "LALT"},
    0xA5: {name:"VK_RMENU", common: "RALT"},
    0xA6: {name:"VK_BROWSER_BACK", common: "BROWSER_BACK"},
    0xA7: {name:"VK_BROWSER_FORWARD", common: "BROWSER_FORWARD"},
    0xA8: {name:"VK_BROWSER_REFRESH", common: "BROWSER_REFRESH"},
    0xA9: {name:"VK_BROWSER_STOP", common: "BROWSER_STOP"},
    0xAA: {name:"VK_BROWSER_SEARCH", common: "BROWSER_SEARCH"},
    0xAB: {name:"VK_BROWSER_FAVORITES", common: "BROWSER_FAVORITES"},
    0xAC: {name:"VK_BROWSER_HOME", common: "BROWSER_HOME"},
    0xAD: {name:"VK_VOLUME_MUTE", common: "VOLUME_MUTE"},
    0xAE: {name:"VK_VOLUME_DOWN", common: "VOLUME_DOWN"},
    0xAF: {name:"VK_VOLUME_UP", common: "VOLUME_UP"},
    0xB0: {name:"VK_MEDIA_NEXT_TRACK", common: "MEDIA_NEXT_TRACK"},
    0xB1: {name:"VK_MEDIA_PREV_TRACK", common: "MEDIA_PREV_TRACK"},
    0xB2: {name:"VK_MEDIA_STOP", common: "MEDIA_STOP"},
    0xB3: {name:"VK_MEDIA_PLAY_PAUSE", common: "MEDIA_PLAY_PAUSE"},
    0xB4: {name:"VK_LAUNCH_MAIL", common: "LAUNCH_MAIL"},
    0xB5: {name:"VK_LAUNCH_MEDIA_SELECT", common: "LAUNCH_MEDIA_SELECT"},
    0xB6: {name:"VK_LAUNCH_APP1", common: "LAUNCH_APP1"},
    0xB7: {name:"VK_LAUNCH_APP2", common: "LAUNCH_APP2"},
    0xBA: {name:"VK_OEM_1", common: "OEM_1"},
    0xBB: {name:"VK_OEM_PLUS", common: "OEM_PLUS"},
    0xBC: {name:"VK_OEM_COMMA", common: "OEM_COMMA"},
    0xBD: {name:"VK_OEM_MINUS", common: "OEM_MINUS"},
    0xBE: {name:"VK_OEM_PERIOD", common: "OEM_PERIOD"},
    0xBF: {name:"VK_OEM_2", common: "OEM_2"},
    0xC0: {name:"VK_OEM_3", common: "OEM_3"},
    0xDB: {name:"VK_OEM_4", common: "OEM_4"},
    0xDC: {name:"VK_OEM_5", common: "OEM_5"},
    0xDD: {name:"VK_OEM_6", common: "OEM_6"},
    0xDE: {name:"VK_OEM_7", common: "OEM_7"},
    0xDF: {name:"VK_OEM_8", common: "OEM_8"},
    0xE2: {name:"VK_OEM_102", common: "OEM_102"},
    0xE5: {name:"VK_PROCESSKEY", common: "PROCESSKEY"},
    0xE7: {name:"VK_PACKET", common: "PACKET"},
    0xF6: {name:"VK_ATTN", common: "ATTN"},
    0xF7: {name:"VK_CRSEL", common: "CRSEL"},
    0xF8: {name:"VK_EXSEL", common: "EXSEL"},
    0xF9: {name:"VK_EREOF", common: "EREOF"},
    0xFA: {name:"VK_PLAY", common: "PLAY"},
    0xFB: {name:"VK_ZOOM", common: "ZOOM"},
    0xFC: {name:"VK_NONAME", common: "NONAME"},
    0xFD: {name:"VK_PA1", common: "PA1"},
    0xFE: {name:"VK_OEM_CLEAR", common: "OEM_CLEAR"}
}

proc.stdout.on("data", function(data){
    let sdata = data.toString().replace(/\s+/,"");
    let arr = sdata.split(",");
    let key = lookupVkeys[parseInt(arr[0])];
    let keyDown = /DOWN/.test(arr[1]);
    let scanCode = parseInt(arr[2]);
    var haltPropogation;
    switch(key.common){
        case "A":
            haltPropogation=true;
            break
        case "CAPSLOCK":
            haltPropogation=true;
            break
        case "B":
            console.log("Quitting " + key.common)
            proc.stdout.pause()
            proc.kill()
            return
        default:
            haltPropogation=false;
    }
    console.log(haltPropogation ? "halted" : "      ", key.common, keyDown ? "DOWN" : "UP  ",scanCode);
    sendPropogate(proc,haltPropogation);
})

function sendPropogate(proc, haltPropogation){
    //If we want to halt propogation send 1, else send 0
    proc.stdin.write(haltPropogation ? "1\n" : "0\n");
}